CREATE TABLE tenant (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
	, name VARCHAR(50) NOT NULL
	, PRIMARY KEY (id)
	);

CREATE TABLE permission (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
	, entity VARCHAR(50) NOT NULL
	, code VARCHAR(50) NOT NULL
	, PRIMARY KEY (id)
	);

CREATE TABLE role (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
	, tenant_id INT(11) UNSIGNED DEFAULT NULL
	, name VARCHAR(50) NOT NULL
	, PRIMARY KEY (id)
	);

CREATE TABLE role_permission (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
	, role_id INT(11) UNSIGNED NOT NULL
	, permission_id INT(11) UNSIGNED NOT NULL
	, PRIMARY KEY (id)
	);

CREATE TABLE user (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
	, role_id INT(11) UNSIGNED NOT NULL
	, name VARCHAR(50) NOT NULL
	, email_address VARCHAR(50) NOT NULL
	, password VARCHAR(20) NOT NULL
	, PRIMARY KEY (id)
	);

CREATE TABLE session (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
	, user_id INT(11) UNSIGNED NOT NULL
	, login_date DATE NOT NULL
	, login_time TIME NOT NULL
	, ip VARCHAR(15) DEFAULT NULL
	, browser VARCHAR(30) DEFAULT NULL
	, os VARCHAR(30) DEFAULT NULL
	, PRIMARY KEY (id)
	);  
